#!/usr/bin/env python3
"""
Build src/assets/platformer_levels.py from all levels/*.txt source files.

Each level's binary data is embedded as a bytes literal so the module can be
frozen into firmware, keeping the bytes in flash rather than heap.

Usage:
    python tools/build_levels.py

Output:
    src/assets/platformer_levels.py   (one attribute per level, e.g. level_01)
"""

import os
import sys

# Allow importing convert_level from the same tools/ directory
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from convert_level import convert

_TOOLS_DIR  = os.path.dirname(os.path.abspath(__file__))
_LEVELS_DIR = os.path.normpath(os.path.join(_TOOLS_DIR, '..', 'levels'))
_OUT_PATH   = os.path.normpath(os.path.join(_TOOLS_DIR, '..', 'src', 'assets', 'platformer_levels.py'))


def main():
    txt_files = sorted(f for f in os.listdir(_LEVELS_DIR) if f.endswith('.txt'))
    if not txt_files:
        print(f'ERROR: no .txt level files found in {_LEVELS_DIR}', file=sys.stderr)
        sys.exit(1)

    lines = [
        '# Auto-generated by tools/build_levels.py — do not edit by hand.',
        '# Each attribute holds the binary level data for one level.',
        '# Frozen into firmware so the bytes live in flash rather than heap.',
        '',
    ]

    total = 0
    for fname in txt_files:
        level_name = fname[:-4]  # strip .txt
        txt_path   = os.path.join(_LEVELS_DIR, fname)
        data = convert(txt_path, level_name, return_bytes=True, quiet=True)
        lines.append(f'{level_name} = {repr(data)}')
        print(f'  {level_name}: {len(data)} bytes')
        total += len(data)

    lines.append('')

    with open(_OUT_PATH, 'w') as fh:
        fh.write('\n'.join(lines))

    print(f'Written: {_OUT_PATH}  ({total} bytes total across {len(txt_files)} levels)')


if __name__ == '__main__':
    main()
